import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import ClientLayout from './GlobalStyling';

//Imported fonts
const font = Quicksand({ subsets: ["latin"], weight:['400','700']})

export const metadata: Metadata = {
  title: "E-comerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}